spring.application.name=cinebook-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cinebook
spring.datasource.username=postgres
spring.datasource.password=80921767

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
jwt.secret=change-this-to-a-long-random-secret-key-for-cinebook-2026

# Razorpay
razorpay.key.id=rzp_test_TOunxVYySisFCh
razorpay.key.secret=0104VPD1PZjJEDJGaPW2vAEr